name: Vanguard

on: workflow_dispatch

env:
  FOUNDRY_PROFILE: ci

jobs:
  build-and-test:
    strategy:
      fail-fast: true

    name: Foundry build & tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run Forge build
        run: |
          forge --version
          forge build --sizes
        id: build

      - name: Run Forge tests
        run: |
          forge test -vvv
        id: test
